language: node_js
node_js:
  - node
  - lts/*

script:
  - npm run lint
  - npm run coverage

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
